clear;
clear all;
% p=parpool(32)
g = MTB.geometry("TaIrTe4");
g = MTB.read_poscar(g,"data/TaIrTe4/POSCAR-TaIrTe4");
[g.ham,g.hopr] = MTB.wannier.read_hr('data/TaIrTe4/wannier90_hr_p1.dat','data/TaIrTe4/wannier90_hr_p2.dat');

efermi=7.3742;
g.wpos=[]
g.wpos=g.atoms*g.a
orbital_num=[
            5,5,5,5,...  % Ta 4 d
            3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,... % Ir 16 p
            5,5,5,5,... % Te 4 d
            5,5,5,5,... % Ta 4 d
            3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,... %Ir 16 p
            5,5,5,5,... % Te 4 d
            ]
g.wpos=[repmat(g.wpos(1,:),[orbital_num(1),1]);...
        repmat(g.wpos(2,:),[orbital_num(2),1]);...
        repmat(g.wpos(3,:),[orbital_num(3),1]);...
        repmat(g.wpos(4,:),[orbital_num(4),1]);...
        repmat(g.wpos(5,:),[orbital_num(5),1]);...
        repmat(g.wpos(6,:),[orbital_num(6),1]);...
        repmat(g.wpos(7,:),[orbital_num(7),1]);...
        repmat(g.wpos(8,:),[orbital_num(8),1]);...
        repmat(g.wpos(9,:),[orbital_num(9),1]);...
        repmat(g.wpos(10,:),[orbital_num(10),1]);...
        repmat(g.wpos(11,:),[orbital_num(11),1]);...
        repmat(g.wpos(12,:),[orbital_num(12),1]);...
        repmat(g.wpos(13,:),[orbital_num(13),1]);...
        repmat(g.wpos(14,:),[orbital_num(14),1]);...
        repmat(g.wpos(15,:),[orbital_num(15),1]);...
        repmat(g.wpos(16,:),[orbital_num(16),1]);...
        repmat(g.wpos(17,:),[orbital_num(17),1]);...
        repmat(g.wpos(18,:),[orbital_num(18),1]);...
        repmat(g.wpos(19,:),[orbital_num(19),1]);...
        repmat(g.wpos(20,:),[orbital_num(20),1]);...
        repmat(g.wpos(21,:),[orbital_num(21),1]);...
        repmat(g.wpos(22,:),[orbital_num(22),1]);...
        repmat(g.wpos(23,:),[orbital_num(23),1]);...
        repmat(g.wpos(24,:),[orbital_num(24),1]);...
        repmat(g.wpos(1,:),[orbital_num(25),1]);...
        repmat(g.wpos(2,:),[orbital_num(26),1]);...
        repmat(g.wpos(3,:),[orbital_num(27),1]);...
        repmat(g.wpos(4,:),[orbital_num(28),1]);...
        repmat(g.wpos(5,:),[orbital_num(29),1]);...
        repmat(g.wpos(6,:),[orbital_num(30),1]);...
        repmat(g.wpos(7,:),[orbital_num(31),1]);...
        repmat(g.wpos(8,:),[orbital_num(32),1]);...
        repmat(g.wpos(9,:),[orbital_num(33),1]);...
        repmat(g.wpos(10,:),[orbital_num(34),1]);...
        repmat(g.wpos(11,:),[orbital_num(35),1]);...
        repmat(g.wpos(12,:),[orbital_num(36),1]);...
        repmat(g.wpos(13,:),[orbital_num(37),1]);...
        repmat(g.wpos(14,:),[orbital_num(38),1]);...
        repmat(g.wpos(15,:),[orbital_num(39),1]);...
        repmat(g.wpos(16,:),[orbital_num(40),1]);...
        repmat(g.wpos(17,:),[orbital_num(41),1]);...
        repmat(g.wpos(18,:),[orbital_num(42),1]);...
        repmat(g.wpos(19,:),[orbital_num(43),1]);...
        repmat(g.wpos(20,:),[orbital_num(44),1]);...
        repmat(g.wpos(21,:),[orbital_num(45),1]);...
        repmat(g.wpos(22,:),[orbital_num(46),1]);...
        repmat(g.wpos(23,:),[orbital_num(47),1]);...
        repmat(g.wpos(24,:),[orbital_num(48),1]);...
    ]
%%
[nbands,~,nrpts]=size(g.ham);
del_index=find(g.wpos(:,3)>6.5342);

%% calculate slab plane bands
MillerIndices=[0,0,1];
Umatrix=g.MillerIndicestoumatrix(MillerIndices);
Urot=g.surfab;
%%
knum=10;
nslab=2;
Occ=120*(nslab-1)+60;
del_index=del_index+(nslab-1)*nbands;



kxline=[0,1];
kyline=[0,1];
[Kx,Ky] = get_Slab2Dkmesh(g,kxline,kyline,knum);
tic;
[Unk,Enk]=MTB.ham.get_slab_plane_bands2(g,del_index,Kx,Ky,nslab);
toc;
Enk=Enk-efermi;

nsbands=1:2;
[Omega_dk,Kx,Ky]=MTB.ham.get_slab_Berrycurvature_dip2_v2(g,del_index,Kx,Ky,Enk,Unk,nsbands,nslab,0.001,0)

%% Write dat and mat for Enk
filename='TaIrTe4_3sEnk-400x400.dat'
writeEnk(Enk,Kx,Ky,Occ,filename)

save("TaIrTe4_3sEnk-400x400.mat","Enk","-v7.3")
delete(p)

%% Enk(nk,nk,nband) Kx(nk,nk) Ky(nk,nk)
function writeEnk(Enk,Kx,Ky,Occ,filename)
    file=fopen(filename, 'w');
    fprintf(file, '%s\n', '# kx     ky     kz     Ev5     Ev4     Ev3     Ev2     Ev1     Ec1     Ec2     Ec3     Ec4     Ec5');
    for i=1:size(Enk,1)
        for j=1:size(Enk,2)
            fprintf(file, [repmat('%12.6f',1,13) '\n'],...
                Kx(i,j), Ky(i,j), 0.0, ...
                Enk(i,j,Occ-4), Enk(i,j,Occ-3), Enk(i,j,Occ-2), Enk(i,j,Occ-1), Enk(i,j,Occ), ...
                Enk(i,j,Occ+1), Enk(i,j,Occ+2), Enk(i,j,Occ+3), Enk(i,j,Occ+4), Enk(i,j,Occ+5));
        end
        fprintf(file,'\n');
    end
    fclose(file);
end
